services:
  - type: web
    name: ckm-risk-calculator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PORT
        value: 8000
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11"
